### ISSUE TITLE
KeyError: 'apiKey'`

### ISSUE THREAD

**Issue by xlly-s** [nhorvath/Pyrebase4#70]
Hey there!

I keep getting this error and can't work out why,
`Traceback (most recent call last):
  File "C:\Users\PC\Documents\FilmBuddy-Reborn-main\main.py", line 33, in <module>
    firebase = pyrebase.initialize_app(firebaseConfig)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrebase\pyrebase.py", line 29, in initialize_app
    return Firebase(config)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyrebase\pyrebase.py", line 35, in __init__
    self.api_key = config["apiKey"]
                   ~~~~~~^^^^^^^^^^
KeyError: 'apiKey'`



Any help is thanked for.

**Comment by arham-sayyed** [comment]
can you please provide the code which is causing this issue? **Most probably, your code is missing one of the config keys,** `apikey`

**Comment by nhorvath** [comment]
closing old issue with no followup
